services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gi_api
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGINS=http://localhost:3001
    ports:
      - "3000:3000"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:3000"
    container_name: gi_web
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - api
    restart: unless-stopped
